scalar Date

type Post {
  id: ID
  content: String
  author: User
  createdAt: Date
}

type user {
  id: ID
  name: String
  username: String
}

input PostInput {
  content: String!
  author: ID!
}

type Mutation {
  createPost(input: PostInput): Post
}

type Query {
  getPostByUser(idUser: ID): [Post]
}
